services:
  db:
    image: postgres:15-alpine
    container_name: dpmg_vagas_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresspassword
      POSTGRES_DB: dpmg_vagas
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
